export const EVENT_ITEMS_INCOMING = "EVENT_ITEMS_INCOMING";
export const EVENT_ITEMS_FETCH = "EVENT_ITEMS_FETCH";
export const EVENT_ITEMS_GRAVITY = "EVENT_ITEMS_GRAVITY";

export const FETCH_ITEMS_INTERVAL_MS = 1000 * 10;
export const APPLY_GRAVITY_INTERVAL_MS = 100;

export const TIME_SCALE = 0.1;
